# Generated by Django 5.1.1 on 2024-10-12 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sortation',
            field=models.CharField(choices=[('공지', 'NOTICE'), ('자유', 'FREE')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='browsing',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_browsing'),
        ),
    ]
